web/code/JobTrak/urls.py
from django.conf.urls import include, url, i18n
#from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from JobTrak.admin import JobTrakAdmin

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
#    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include (JobTrakAdmin.urls)),
    url(r'', include('external_urls.urls')),
]

urlpatterns += i18n.i18n_patterns(
    url(r'^app/contact/', include('mmg.jobtrak.contact.urls', namespace='contact')),
    url(r'^app/jobboards/', include('mmg.jobtrak.links.urls', namespace='jobboard')),
    url(r'^app/', include('mmg.jobtrak.core.urls', namespace='core')),
    url(r'^', include('mmg.jobtrak.public.urls')),
)

web/code/mmg/jobtrak/contact/urls.py
from django.conf.urls import url
from mmg.jobtrak.contact import views

urlpatterns = [
    url(r'^view/(\d+)/$', views.contact_detail, name='contact_detail'),
    url(r'^$', views.contact_list, name='contact_list'),
]

web/code/mmg/jobtrak/core/urls.py
from django.conf.urls import include, url, i18n
from mmg.jobtrak.core import views

urlpatterns = [
    url(r'^joblistings/$', views.job_list, name="job_list"),
    url(r'^joblistings/(?P<id>[0-9]+)/$', views.job_detail, name='job_detail'),
    url(r'^$',views.index,name='index'),
]

web/code/files/templates/base/base.html
{% extends 'base/bootstrap.html' %}
{% load bootstrap3 i18n %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
{% if user.is_authenticated %}
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">
    	<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">{% trans 'Toggle Nav' %}</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'core:index' %}">JobTrak</a>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<!-- <li><a href="{% url 'core:index' %}">{% trans 'Home' %}</a></li> -->
				<li><a href="{% url 'core:job_list' %}">{% trans 'Listings' %}</a></li>
				<!-- <li><a href="{% url 'contact:contact_list' %}">{% trans 'Contacts' %}</a></li> -->
				<li><a href="{% url 'jobboard:index' %}">{% trans 'Job Boards' %}</a></li>
<!--
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Menu Item <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="#">Item</a></li>
						<li><a href="#">Item</a></li>
						<li><a href="#">Item</a></li>
					</ul>
				</li>
//-->
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"
						role="button" aria-expanded="false"><img class="gravatar"
						src="http://www.gravatar.com/avatar/5eb177439e0abfeb0d074b67deea792c?s=24" alt="" />
						{% firstof user.get_full_name user.get_short_name user.get_username %} <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="{% url "admin:index" %}">{% trans 'Manage' %}</a></li>
						<li><a href="{% url "admin:logout" %}">{% trans 'Log Out' %}</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>
{% endif %}
<div class="container">
	<div class="row">
		{% block breadcrumb %}{% endblock %}
    {% bootstrap_messages %}
	</div>
    {% block content %}(no content){% endblock %}
</div>
<!-- TODO: Footer will go here. -->
{% endblock %}

web/code/files/templates/base/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}{% load static from staticfiles %}
{% block bootstrap3_extra_head %}
<link href="https://fonts.googleapis.com/css?family=Alegreya|Ruda" rel="stylesheet">
<link href="{% static 'libs/theme.css'  %}" rel="stylesheet">
{% endblock %}

{% block bootstrap3_title %}{% block title %}{% endblock %} | JobTrak{% endblock %}